# Created using winget-create 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
# NOTE: Replace InstallerSha256 with actual hash before submitting to winget-pkgs
#       Calculate with: Get-FileHash nvtop-3.3.0-windows-x64.zip -Algorithm SHA256

PackageIdentifier: Nervosys.Nvtop
PackageVersion: 3.3.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Commands:
- nvtop
ReleaseDate: 2025-11-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nervosys/nvtop/archive/refs/tags/v3.3.0.zip
  InstallerSha256: 61fe4424c9ccc87700777a8d4f6526f414b3c9f0dc3106ed83b8edc783483be0
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: nvtop.exe
    PortableCommandAlias: nvtop
ManifestType: installer
ManifestVersion: 1.6.0
